server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://my8002.gabiadb.com/amsdb
    username: amsdb
    password: ghrn1004!!

    dbcp2:
      validation-query: SELECT 1

  hikari:
    auto-commit: true
    maximum-pool-size: 20     # 최대 커넥션 풀 크기, 10개로 설정
    minimum-idle: 5           # 최소 유휴 커넥션 수, 5개로 설정
    connection-timeout: 3000
    validation-timeout: 3000
    idle-timeout: 300000       # 유휴 커넥션 최대 대기 시간, 5분으로 설정
    max-lifetime: 240000      # 커넥션 풀에서 커넥션의 최대 수명, 30분으로 설정

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

mybatis:
  mapper-locations: classpath:sql/*.xml

logging:
  level:
    root: INFO
    org.springframework.security: INFO


